In [22]:
import numpy as np

def checkerboard():
    checkerboard = np.zeros((8, 8), dtype=int)
    checkerboard[1:8:2, 1:8:2] = 1
    checkerboard[0:8:2, 0:8:2] = 1
    print(checkerboard)

checkerboard()

[[1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]]
