In [9]:
import numpy as np
def sorting(a):
    rows, cols = a.shape
    for col in range(0, cols):
        for i in range(rows - 1):
            for j in range(0, rows - i - 1):
                if a[j, col] > a[j + 1, col]:
                    a[j, col], a[j + 1, col] = a[j + 1, col], a[j, col]
    print(a)

np.random.seed(12345)
a = np.random.randint(1,50, (4,5))
sorting(a)


[[12 14 11  2  2]
 [15 38 28 17 10]
 [35 38 30 18 19]
 [42 42 35 30 37]]
